### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by EricGlaenzer** [faceair/atom-goto-definition#10]
Since Javascript seems to be not supported, I went ahead to uninstall this package and this also failed:
Uninstalling “goto-definition” failed.Hide output…

And the details shows:
"Failed to delete goto-definition: Does not exist"

This is happening on a Mac OSX, latest version of the OS.

**Comment by faceair** [comment]
I have met this problem some times, maybe it caused by Atom. Most times when I reload the editor, the uninstall will have been completed.

**Comment by EricGlaenzer** [comment]
True, when I restarted Atom I didn't have the package anymore, but I still think there is an issue during uninstallation. Unfortunately I am not expert enough to help on this.
