### ISSUE TITLE
searches vcs ignored paths, even though "Exclude VCS Ignored Paths" is enabled

### ISSUE THREAD

**Issue by duanefields** [faceair/atom-goto-definition#12]
At least in Atom 1.8, it happily searches in node_modules, build, etc. even though these are excluded.

**Comment by israelglass123** [comment]
I also have this issue

**Comment by savbace** [comment]
+1 for Atom 1.8

**Comment by faceair** [comment]
Hi everyone, I have fixed it and released an new version. Cheers! 🍻
