### ISSUE TITLE
Does not skip compiled Javascript folder

### ISSUE THREAD

**Issue by niranjan92** [faceair/atom-goto-definition#19]
I want to skip compiled javascript folder eg. JS generated by Babel in a separate folder in my project. I couldn't find any way to do that.

How do I skip a particular folder in my project from search?

**Comment by faceair** [comment]
See https://github.com/faceair/atom-goto-definition#ignoring-files

**Comment by davidbarredo** [comment]
Maybe it worth it to use the .gitignore file instead of create a new one to add the same folders in both.
