### ISSUE TITLE
alt+click support

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [faceair/atom-goto-definition#25]
it would be really good if this plugin supported alt+mouse click like this https://atom.io/packages/hyperclick

**Comment by hjinu** [comment]
👍

**Comment by ffxsam** [comment]
I came here to report the same. The cmd+click interferes with the duplicate cursor function.

**Comment by r-chris** [comment]
Some OS (e.g. Ubuntu) reserve Alt+Click to moving the window - not sure if this would work there? The demo looks great, though!

**Comment by faceair** [comment]
Now, we have been supported hyperclick ! 😄
