### ISSUE TITLE
Performance Mode Missing in Settings

### ISSUE THREAD

**Issue by aryeh-looker** [faceair/atom-goto-definition#44]
Looking forward to checking out this package a bit more! I couldn't seem to find a setting for performance mode as articulated here (https://github.com/faceair/atom-goto-definition#performance-mode). Could there have been a regression? Thank you kindly all your hard work on this package.

**Comment by faceair** [comment]
We have not released this version. Now you can use `apm install https://github.com/faceair/atom-goto-definition.git` to preview.

I have a little work on this, after the completion I will release a new version, probably in today or tomorrow.

**Comment by faceair** [comment]
Version 1.3.0 has been released.
