### ISSUE TITLE
Performance Mode issue

### ISSUE THREAD

**Issue by moonbas3** [faceair/atom-goto-definition#47]
Hello,

I've installed ripgrep manually by copying the binary to /usr/bin, enabled performance mode and tried to do a go-to-definition. Unfortunately, it doesn't return any results, doesn't even try, just says that 'there are no definitions'.
If I disable performance mode, the usual search happens and actually works.

Do you have any ideas about this or maybe places where I could look to trace this error down maybe ? I've looked through the console, but nothing is outputted.

Maybe I did not install ripgrep properly ? But I think I did, I have the rg command available everywhere now (hmm, I guess that it's just for my user, but I don't run atom as sudo).
Also, it works on my system and it is insanely fast, I cannot believe my eyes.

Specs:
goto-definition 1.3.0
atom 1.15.0
KDE Neon 5.9.4 (kernel 4.4.0-64)

Thank you.

**Comment by faceair** [comment]
I guess it might be a regular expression wrong.

please help me do this:
1. open `Settings`-> `Packages` -> `Goto Definition` -> `View Code`
2. inserted
```
console.log scan_paths
console.log file_types
console.log regex
```
into the middle of [goto-definition.coffee](https://github.com/faceair/atom-goto-definition/blob/275e1eac74fa8da12e213606d00469ad49b90c64/lib/goto-definition.coffee#L120)'s 120 lines and 121 lines.
3. reload the window.
4. use the `goto-definition:go` command, and get the `scan_paths` `file_types` and `regex` in console.

And you also should give me the example code, let me to reproduce the error.

Thanks.

**Comment by faceair** [comment]
🤔 Maybe I should add an debug mode to collecting logs.

**Comment by moonbas3** [comment]
Hello

I followed your instructions and did some more testing and I eventually found out that **this is happening when I have multiple folders open in my project.**
When I hit view code on your extension it opened a new window with only one project folder and when I tried to go to a function, it worked. I was able to reproduce this behaviour with my other project as well.

[screenshot_20170329_162210](https://cloud.githubusercontent.com/assets/1404954/24456868/082a4f0c-149d-11e7-9801-87f4d4efb753.png)
This is the console output from those variables, everything seems to be fine. I also checked the regex with an online tool as I am not that experienced with it. The target is a wordpress install and [here's](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/load.php#L55) the exact function definition.

Regex
```regex
(^|\s)class\s+wp_fix_server_vars(\s|\{|$)|(^|\s)interface\s+wp_fix_server_vars(\s|\{|$)|(^|\s)trait\s+wp_fix_server_vars(\s|\{|$)|(^|\s)(static\s+)?((public|private|protected)\s+)?(static\s+)?function\s+wp_fix_server_vars\s*\(|(^|\s)const\s+wp_fix_server_vars(\s|=|;|$)
```

Is this maybe a known issue ? Or do you have any ideas why it might happen ?

Thanks.

**Comment by faceair** [comment]
Thanks for you report, I have fixed it.
Now, you can patch [this commit](https://github.com/faceair/atom-goto-definition/commit/e103b8c1e003d8673b9ef3877440bea532f7aa23) to make that work. I will release the new version in this weekend.

**Comment by moonbas3** [comment]
Thank you, it works !
