### ISSUE TITLE
Unknown keyword 

### ISSUE THREAD

**Issue by JulianJP** [faceair/atom-goto-definition#48]
![captura de pantalla de 2017-04-03 15-40-52](https://cloud.githubusercontent.com/assets/6529158/24630897/004c50d8-1884-11e7-8fc6-967fcf263901.png)

**Comment by JulianJP** [comment]
When i execute the command

**Comment by faceair** [comment]
I did not see the cursor on the screenshot. Where is your mouse ?

**Comment by vasyl-shumskyi** [comment]
same here
