### ISSUE TITLE
Interferes w/ hyperlink-hyperclick

### ISSUE THREAD

**Issue by black-snow** [faceair/atom-goto-definition#49]
Sadly, for some months now, goto-definition seems to interfere with [hyperlink-hyperclick](https://github.com/UziTech/hyperlink-hyperclick).

With goto-definition disabled URLs get highlighted correctly and hyperlink works as expected. With goto-definition enabled just parts of the URL get highlighted, there's no way to click+open any URLs.
It sometimes works when disabling and re-enabling both plugins in some magic order.

**Comment by faceair** [comment]
https://atom.io/packages/hyperclick

Hyperclick only returns suggestions from a single provider, and provide an option `priority` to override others. You can send an pull request to hyperlink-hyperclick, set `priority` before [main.js#92L](https://github.com/UziTech/hyperlink-hyperclick/blob/master/lib/main.js#L92). goto-definition not set `priority`, the default value is `0`, hyperlink-hyperclick's `priority` should be greater than it.

**Comment by black-snow** [comment]
@faceair thanks
