### ISSUE TITLE
Language not supported since version 1.3.1

### ISSUE THREAD

**Issue by ptrckmrx** [faceair/atom-goto-definition#50]
When trying to use goto-definition via cmd + click on a word I get this error, no matter what language or file type.
![bildschirmfoto 2017-04-06 um 09 43 25](https://cloud.githubusercontent.com/assets/15648983/24743306/fe14ec86-1aad-11e7-88f2-07acb7cbf06b.png)

**Comment by faceair** [comment]
Please tell me some file types.

**Comment by ptrckmrx** [comment]
Hey faceair, the error occurs in **.scss**, **.ts** and **.tsx** files. Thanks!

**Comment by faceair** [comment]
Now we don't support `.scss` and `.tsx`, but support `.ts`. I have just tested `.ts` and it is working properly.

**Comment by faceair** [comment]
Can you help test other languages? Such as Python or JavaScript.

**Comment by ptrckmrx** [comment]
Okay, do you plan on adding support for .scss and .tsx in the future?

I already tested JavaScript, HTML and PHP, all seem to work. Unfortunately I don't use Python myself.

**Comment by faceair** [comment]
There is no plan yet, pull request welcome.
Look at this https://github.com/faceair/atom-goto-definition/blob/master/lib/config.js to add new language support, not complicated.
