### ISSUE TITLE
How do I properly setup ripgrep for performance mode

### ISSUE THREAD

**Issue by v-vincere** [faceair/atom-goto-definition#55]
Hey I am trying to get performance mode to work within Atom I have downloaded ripgrep and have rg.exe have setup my PATH to point to it, however when I try to use goto-definition with performance mode on it keeps telling me "Please install ripgrep first". How do I properly setup ripgrep so I can use performance mode? Thanks

**Comment by v-vincere** [comment]
Scratch that I was to hasty and figured it out. Just had to restart Atom lol

**Comment by faceair** [comment]
😀
