### ISSUE TITLE
support C/C++

### ISSUE THREAD

**Issue by GusSand** [faceair/atom-goto-definition#8]
Could you please support C/C++ ? It would be aweome.

**Comment by requiemforameme** [comment]
Hmmm... I'm trying to think about how that would work.  There would need to be search capabilities for the header  (`.h`) files?

**Comment by cblack3** [comment]
My team would really like this as well

**Comment by albert-tomanek** [comment]
Same here

**Comment by r-chris** [comment]
Basic C/C++ support has been merged and released - please provide PRs for additional features.
