### ISSUE TITLE
This language is not supported

### ISSUE THREAD

**Issue by starInEcust** [faceair/atom-goto-definition#9]
全是.js后缀啊~ 在哪按都是这句话，还带一个笑脸... 是不是这个插件的bug？

**Comment by faceair** [comment]
你有用一些语言特性增强相关的插件么？在窗口右下角是显示的什么语言名称？

**Comment by starInEcust** [comment]
javascript by subtleGradient 还有 JavaScript with JSX 都不行。 我发现js-hyperclick可以跳啊~ 我对不起你啊 我就用这个了....

**Comment by faceair** [comment]
现在语言判断的部分是有些死板，我知道怎么改进了。非常感谢你的反馈，等我修好了再关这个 issue : )

**Comment by EricGlaenzer** [comment]
This bug happens to me with Javascript.

**Comment by faceair** [comment]
@EricGlaenzer @lorrocha 

I released a new version to fix it. Maybe you can have a try.

**Comment by EricGlaenzer** [comment]
Yes! much better! Thank you for this package this is awesome!

**Comment by starInEcust** [comment]
哦~ 我出去旅个游你就修好啦！ 好厉害！
